spring.datasource.url=jdbc:mysql://localhost:3306/chatdb?createDatabaseIfNotExist=true
spring.data.mongodb.uri = mongodb://localhost:27017/chatdb
app.security.public-get-paths=…, /swagger-ui/**, /swagger-ui.html, /v3/api-docs/**