spring.datasource.url=jdbc:mysql://localhost:3306/mediadb?createDatabaseIfNotExist=true
app.security.public-get-paths=/mediaStore/adverts/**,/mediaStore/profiles/*/load/**
app.security.public-get-paths=…, /swagger-ui/**, /swagger-ui.html, /v3/api-docs/**